# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
update: true
install: travis_wait mvn install

os:
  - linux
  - osx

r:
  - 3.5
  - release
  
after_success:
    - Rscript -e 'covr::codecov( type = "all")'

